// 尺寸单位为米。经纬度为场地概略定位，不用于导航或设施测绘。
export const ROCKET = {
  id: 'falcon9',
  name: '猎鹰 9 号',
  englishName: 'Falcon 9',
  variant: 'Block 5 · 卫星整流罩构型',
  configuration: '两级液体火箭 · 可回收一级 · 卫星整流罩',
  height: 70,
  diameter: 3.7,
  firstStageEngines: 9,
  secondStageEngines: 1,
  gridFins: 4,
  landingLegs: 4,
  description: '从点火升空到级间分离，观察两级火箭如何协作；在拆解视图中认识发动机、整流罩与回收部件。',
  accuracy: '全箭高度与芯级直径采用官方公开值；模块比例、表面细节和运动过程为科普示意。',
};

export const SITES = [
  {
    id: 'slc40',
    name: '卡纳维拉尔角 · SLC-40',
    shortName: '卡纳维拉尔角',
    region: '美国 · 佛罗里达州',
    lat: 28.56,
    lon: -80.58,
    description: '位于佛罗里达州大西洋沿岸的猎鹰 9 号发射场。此场景以低平海岸为背景；位置为概略定位，设施为示意。',
    terrain: 'coast',
    padLabel: 'SLC-40',
  },
  {
    id: 'lc39a',
    name: '肯尼迪航天中心 · LC-39A',
    shortName: '肯尼迪航天中心',
    region: '美国 · 佛罗里达州',
    lat: 28.61,
    lon: -80.60,
    description: '位于肯尼迪航天中心、支持猎鹰 9 号的发射场。此处使用卫星整流罩构型；位置为概略定位，塔架与平台为示意。',
    terrain: 'coast',
    padLabel: 'LC-39A',
  },
  {
    id: 'slc4e',
    name: '范登堡 · SLC-4E',
    shortName: '范登堡',
    region: '美国 · 加利福尼亚州',
    lat: 34.63,
    lon: -120.61,
    description: '位于加利福尼亚州太平洋沿岸的猎鹰 9 号发射场。场景用西海岸丘陵表现环境差异；位置为概略定位，地形为示意。',
    terrain: 'west',
    padLabel: 'SLC-4E',
  },
];

export const MODULES = [
  {
    id: 'stage1',
    name: '第一级',
    subtitle: '将火箭带离地面',
    description: '第一级装载液氧与火箭煤油，并通过底部发动机组提供起飞推力。完成上升段任务后与第二级分离；具备回收条件的任务可让它返回着陆。',
    facts: ['推进剂：液氧与 RP-1 火箭煤油', '芯级直径：3.7 米', '一级回收方式随具体任务变化'],
    accuracy: '公开结构；舱段长度、储箱内部与表面细节为示意',
  },
  {
    id: 'engines1',
    name: '一级发动机组',
    subtitle: '九台 Merlin 发动机',
    description: '九台 Merlin 发动机组成一级动力系统。八台围绕中央一台排列，点火后推动整枚火箭升空。',
    facts: ['发动机数量：9 台', '布局：中央 1 台，外围 8 台', '动画火焰用于表现工作状态'],
    accuracy: '发动机数量与总体布局依据公开资料；喷管和火焰为视觉示意',
  },
  {
    id: 'interstage',
    name: '级间段',
    subtitle: '连接两级的结构',
    description: '级间段连接第一级与第二级，并围绕二级发动机所在空间。飞行中两级分离；拆解视图将它单独展开，方便理解连接关系。',
    facts: ['连接第一级与第二级', '围绕二级发动机空间', '教学拆解不等于真实装配或分离流程'],
    accuracy: '公开结构；连接机构与尺寸细节为示意',
  },
  {
    id: 'stage2',
    name: '第二级',
    subtitle: '继续加速并运送载荷',
    description: '与第一级分离后，第二级继续工作，将载荷送往目标轨道。具体点火次数、工作时长和载荷释放时间由任务决定。',
    facts: ['推进剂：液氧与 RP-1 火箭煤油', '由 1 台真空型 Merlin 发动机提供动力', '任务不同，飞行时间轴也不同'],
    accuracy: '公开结构；长度比例、轨迹和工作时长按教学用途简化',
  },
  {
    id: 'engine2',
    name: '二级真空发动机',
    subtitle: 'Merlin Vacuum',
    description: '二级使用适合低压环境工作的 Merlin 真空发动机。其较大的喷管有助于在高空和太空中利用燃气膨胀做功。',
    facts: ['发动机数量：1 台', '用于第二级推进', '喷管外形与工作火焰仅作科普展示'],
    accuracy: '公开工作原理；喷管几何与内部结构未作工程还原',
  },
  {
    id: 'fairing-left',
    name: '整流罩 · 左半罩',
    subtitle: '保护载荷的外壳',
    description: '整流罩在火箭穿越稠密大气时保护载荷。达到合适的飞行条件后，两半罩分离，露出内部载荷。左右名称仅用于当前视图辨认。',
    facts: ['卫星发射构型的保护外壳', '与另一半罩共同包围载荷', '分离时刻按具体任务确定'],
    accuracy: '两半罩结构依据公开资料；曲面、厚度和分离运动为示意',
  },
  {
    id: 'fairing-right',
    name: '整流罩 · 右半罩',
    subtitle: '与左半罩共同保护载荷',
    description: '这部分与左半罩闭合形成整流外形。拆解展示用于理解保护壳和载荷的位置关系，不代表真实工装或维修操作。',
    facts: ['与左半罩组成完整整流罩', '随任务安排实施分离', '左右标记属于教学视图'],
    accuracy: '两半罩结构依据公开资料；连接件与表面细节为示意',
  },
  {
    id: 'payload',
    name: '示例卫星载荷',
    subtitle: '本次任务的乘客',
    description: '这里放置一颗虚构的教学卫星，帮助观察整流罩内部空间和载荷释放过程。它不对应任何真实任务的卫星型号。',
    facts: ['虚构教学模型', '不代表真实卫星尺寸或质量', '载荷释放过程为简化展示'],
    accuracy: '教学创作，无真实型号对应',
  },
  {
    id: 'grid-fins',
    name: '栅格翼',
    subtitle: '返航时的气动控制部件',
    description: '四片栅格翼位于一级上部，在大气中的返航阶段帮助控制姿态和航向。它们需要气流才能产生气动力。',
    facts: ['数量：4 片', '用于一级在大气中的返航控制', '不是依靠栅格翼在真空中转向'],
    accuracy: '数量与用途依据公开资料；网格、转轴与动作幅度为示意',
  },
  {
    id: 'landing-legs',
    name: '着陆腿',
    subtitle: '为一级着陆提供支撑',
    description: '四条着陆腿在起飞时收拢，着陆前展开，为一级接触着陆面提供支撑。展开动作和接地效果在此经过简化。',
    facts: ['数量：4 条', '起飞时收拢，着陆前展开', '具体回收地点取决于任务'],
    accuracy: '数量与用途依据公开资料；机械结构与缓冲过程为示意',
  },
];

export const SOURCES = [
  {
    title: 'SpaceX · Falcon 9 官方介绍',
    url: 'https://new.spacex.com/vehicles/falcon-9',
    note: '全箭高 70 米、芯级直径 3.7 米、两级结构及发动机、栅格翼与着陆腿的公开介绍。',
  },
  {
    title: 'SpaceX · Falcon 用户指南（2025-05-09）',
    url: 'https://www.spacex.com/assets/media/falcon-users-guide-2025-05-09.pdf',
    note: '公开任务样例、火箭结构与发射场资料。样例事件不能解释为本游戏对某次真实飞行的完整复现。',
  },
];
