// Studio presets are shared by structure exploration and assembly only.
// They do not change rocket materials, propellant legend colours or launch sites.
// Colour strings are sRGB; let THREE.Color perform its normal conversion.
export const DEFAULT_STUDIO_THEME_ID = 'technology';

export const STUDIO_THEMES = Object.freeze([
  {
    id: 'technology',
    name: '科技展厅',
    subtitle: '明亮蓝灰，慢慢看清每个部件',
    background: '#9cb5c5',
    ground: '#859ead',
    platform: '#667f91',
    grid: '#627d91',
    gridCenter: '#c2dce8',
    hemisphereSky: '#e6f5ff',
    hemisphereGround: '#718895',
    hemisphereIntensity: 2.1,
    keyColor: '#fff6e9',
    keyIntensity: 2.8,
    rimColor: '#c2e4ff',
    rimIntensity: 1.2,
    fillColor: '#e8f4ff',
    fillIntensity: 0.9,
    exposure: 1.0,
    environmentIntensity: 0.38,
    showStars: false,
    ui: {
      panel: '#f1f7fa',
      surface: '#dce8f0',
      text: '#162b3b',
      muted: '#496373',
      line: '#b5c8d4',
      accent: '#176f9b',
    },
  },
  {
    id: 'realistic',
    name: '摄影工作室',
    subtitle: '暖白柔光，观察外壳和连接处',
    background: '#d4cbbd',
    ground: '#c3b7a5',
    platform: '#a99c89',
    grid: '#a99a84',
    gridCenter: '#eee3cf',
    hemisphereSky: '#fff7e9',
    hemisphereGround: '#8d7b68',
    hemisphereIntensity: 1.85,
    keyColor: '#fff4df',
    keyIntensity: 2.65,
    rimColor: '#edf4ff',
    rimIntensity: 1.0,
    fillColor: '#e2edff',
    fillIntensity: 0.8,
    exposure: 0.96,
    environmentIntensity: 0.34,
    showStars: false,
    ui: {
      panel: '#fffaf1',
      surface: '#e9e0d0',
      text: '#372f28',
      muted: '#6c5e4e',
      line: '#c7bba7',
      accent: '#8a562d',
    },
  },
  {
    id: 'playful',
    name: '火箭小工坊',
    subtitle: '奶油与天空色，动手拼一拼',
    background: '#b7d6e0',
    ground: '#e3d6b9',
    platform: '#cbb995',
    grid: '#a9c3c8',
    gridCenter: '#fff1cc',
    hemisphereSky: '#f4fcff',
    hemisphereGround: '#b5a589',
    hemisphereIntensity: 2.2,
    keyColor: '#fff3d8',
    keyIntensity: 2.4,
    rimColor: '#bceaff',
    rimIntensity: 1.15,
    fillColor: '#fff8ec',
    fillIntensity: 1.0,
    exposure: 1.0,
    environmentIntensity: 0.3,
    showStars: false,
    ui: {
      panel: '#fff7e4',
      surface: '#f0e1c0',
      text: '#293545',
      muted: '#535c69',
      line: '#c9b98e',
      accent: '#a24b23',
    },
  },
  {
    id: 'space',
    name: '星空展台',
    subtitle: '蓝紫星空，也能看清深色零件',
    background: '#43496d',
    ground: '#3a4668',
    platform: '#68779a',
    grid: '#6b7fa4',
    gridCenter: '#b5cbe8',
    hemisphereSky: '#d8e4ff',
    hemisphereGround: '#7380a2',
    hemisphereIntensity: 2.4,
    keyColor: '#f5f2ff',
    keyIntensity: 3.0,
    rimColor: '#b1c9ff',
    rimIntensity: 1.55,
    fillColor: '#f0deff',
    fillIntensity: 1.1,
    exposure: 1.06,
    environmentIntensity: 0.4,
    showStars: true,
    ui: {
      panel: '#25314a',
      surface: '#34445e',
      text: '#f0f5ff',
      muted: '#c1cee0',
      line: '#62718c',
      accent: '#ffd495',
    },
  },
].map(theme => Object.freeze({ ...theme, ui: Object.freeze(theme.ui) })));

/** Unknown or absent saved preferences use the bright technology studio. */
export function getStudioTheme(id = DEFAULT_STUDIO_THEME_ID) {
  return STUDIO_THEMES.find(theme => theme.id === id) || STUDIO_THEMES[0];
}
